### ISSUE TITLE
Better test constraints

### ISSUE THREAD

**Issue by amontoison** [JuliaSmoothOptimizers/NLPModelsTest.jl#109]
Instead of testing `norm(c(x))`, we should test `norm(c(x)) - lcon` and `norm(c(x)) - ucon`.
Some constants in `c(x)` are sometimes moved in the bounds.
Tests could fail because of that.

cc @tmigot

**Comment by tmigot** [comment]
We handle this correctly. The problem was more that the error message was not pointing to the fact that SlackModel were failing.
I am closing in favor of #57
