### ISSUE TITLE
@tmigot A test should be updated in `NLPModelsTest.jl`:

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/NLPModelsTest.jl#113]
@tmigot A test should be updated in `NLPModelsTest.jl`:
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/actions/runs/11040944389/job/30670104859?pr=304#step:6:444

_Originally posted by @amontoison in https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/issues/304#issuecomment-2375286258_

**Comment by amontoison** [comment]
We could maybe use an interval of bits to support both old and new versions of Julia?
