### ISSUE TITLE
Add unit tests for linear and nonlinear API

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/NLPModelsTest.jl#35]
From `NLPModels.jl` 0.18 we have access to the linear constraints.
We will need to add unit tests for the linear and nonlinear API.

- [x] Add linear API in test problems
- [x] Add tests in check-dimensions.jl
- [x] Add tests in multi-precision.jl
- [x] Add tests in coord-memory.jl
- [x] Add tests in consistency.jl in the function  consistent\_counters
- [x] Add linear API for quasi-Newton models (NLPModelsModifiers.jl)
- [x] Add linear API for slack models (NLPModelsModifiers.jl)
- [x] ~~Add line API for FeasibilityFormNLS  models (NLPModelsModifiers.jl)~~
- [ ] Add tests in consistency.jl in the function  consistent\_functions

**Comment by tmigot** [comment]
I gave up on the `Add line API for FeasibilityFormNLS models (NLPModelsModifiers.jl)`, because it would require access to the linear part of the residual. So, I suggest we make an issue for this on NLPModelsModifiers.jl for later, and skip this in the consistency checks in NLPModelsTest.

**Comment by abelsiqueira** [comment]
I agree. Can you create the issue and close this afterwards?
